### ISSUE TITLE
incompatible with newer version of laravel.

### ISSUE THREAD

**Issue by chenghung** [OnrampLab/laravel-log-enhancement#13]
```
/html/vendor/onramplab/laravel-log-enhancement/src/LogManager.php on line 57
neo-backend-php-1  | 
neo-backend-php-1  |    Symfony\Component\ErrorHandler\Error\FatalError 
neo-backend-php-1  | 
neo-backend-php-1  |   Declaration of Onramplab\LaravelLogEnhancement\LogManager::get($name) must be compatible with Illuminate\Log\LogManager::get($name, ?array $config = null)
neo-backend-php-1  | 
neo-backend-php-1  |   at vendor/onramplab/laravel-log-enhancement/src/LogManager.php:57
neo-backend-php-1  |      53▕      *
neo-backend-php-1  |      54▕      * @param  string  $name
neo-backend-php-1  |      55▕      * @return \Psr\Log\LoggerInterface
neo-backend-php-1  |      56▕      */
neo-backend-php-1  |   ➜  57▕     protected function get($name)
neo-backend-php-1  |      58▕     {
neo-backend-php-1  |      59▕         try {
neo-backend-php-1  |      60▕             return $this->channels[$name] ?? with($this->resolve($name), function ($logger) use ($name) {
neo-backend-php-1  |      61▕                 return $this->channels[$name] = $this->tap($name, new Logger($logger, $this->app['events']));
neo-backend-php-1  | PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
neo-backend-php-1  | Stack trace:
neo-backend-php-1  | #0 /var/www/html/vendor/composer/ClassLoader.php(578): Whoops\Run->handleError()
neo-backend-php-1  | #1 /var/www/html/vendor/composer/ClassLoader.php(578): include()
neo-backend-php-1  | #2 /var/www/html/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
neo-backend-php-1  | #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
neo-backend-php-1  | #4 /var/www/html/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
neo-backend-php-1  | #5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
neo-backend-php-1  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
neo-backend-php-1  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
neo-backend-php-1  | #8 /var/www/html/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
neo-backend-php-1  | #9 /var/www/html/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
neo-backend-php-1  | #10 /var/www/html/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
neo-backend-php-1  | #11 /var/www/html/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
neo-backend-php-1  | #12 /var/www/html/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
neo-backend-php-1  | #13 /var/www/html/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(72): NunoMaduro\Collision\Handler->handle()
neo-backend-php-1  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(185): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole()
neo-backend-php-1  | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(171): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
neo-backend-php-1  | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(209): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
neo-backend-php-1  | #17 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
neo-backend-php-1  | #18 {main}
neo-backend-php-1  |   thrown in /var/www/html/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52

```

**Comment by chenghung** [comment]
closed due to this issue already fixed in latest version.
